import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.VERIFY_URL||'http://localhost:4175/',runs=(process.env.RUNS||'reference,before').split(','),cases=(process.env.CASES||'L2,L3,main').split(','),shots=process.argv.includes('--shots'),count=Number(process.env.COUNT||220);
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-webgpu','--use-angle=metal','--ignore-gpu-blocklist']}),page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1.5}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const q=(a,p)=>[...a].sort((a,b)=>a-b)[Math.floor((a.length-1)*p)]||0,mean=a=>a.reduce((a,b)=>a+b,0)/a.length,round=n=>+n.toFixed(4);
async function release(run,scenario,stop=Infinity){
 const lab=scenario!=='main',profile=run.startsWith('reference')?'legacy':'launch';
 await page.goto(`${base}?burstProbe&physics=${profile}&burst=${run}&camera=default${lab?`#/lab/shatter?level=${scenario.slice(1)}`:''}`);
 if(lab){await page.waitForFunction(()=>window.lab?.ready,null,{timeout:90000});await page.evaluate(count=>window.lab.setReveal({freeze:true,count}),count);await page.keyboard.press('r');await page.waitForFunction(()=>window.lab.state.elapsed===0&&!window.lab.state.broken);await page.evaluate(stop=>window.burstProbe.stopAt=stop,stop);const p=await page.evaluate(()=>window.lab.state.paneCenter);await page.mouse.click(p.x,p.y);await page.evaluate(()=>window.lab.setReveal({freeze:false}));}
 else{await page.waitForFunction(()=>window.aquarium?.elapsed>2,null,{timeout:90000});await page.evaluate(stop=>window.burstProbe.stopAt=stop,stop);await page.keyboard.press('Space');}
}
try{for(const run of runs){await mkdir(`verify/burst-${run}`,{recursive:true});for(const scenario of cases){
 if(shots){if(scenario!=='L3')continue;for(const t of [.15,.4]){await release(run,scenario,t);await page.waitForFunction(t=>window.lab.state.elapsed>=t-1e-8,t);await page.waitForTimeout(150);const dir=run==='reference'?'verify/perf-before':run==='after'?'verify/perf-after':'verify/burst-before';await mkdir(dir,{recursive:true});const snapshot=await page.evaluate(()=>window.lab.state);assert.ok(Math.abs(snapshot.elapsed-t)<1e-8);await writeFile(`${dir}/lab-L3-burst-${String(Math.round(t*100)).padStart(3,'0')}.json`,JSON.stringify(snapshot,null,2));await page.screenshot({path:`${dir}/lab-L3-burst-${String(Math.round(t*100)).padStart(3,'0')}.png`});console.log(`FRAME ${run} L3 ${t.toFixed(2)}s ${dir}`);}continue;}
 await release(run,scenario);await page.waitForFunction(()=>window.burstProbe.steps.length>=30).catch(async e=>{console.log('DEBUG',await page.evaluate(()=>({n:window.burstProbe.steps.length,start:window.burstProbe.start,count:window.burstProbe.count,last:window.burstProbe.steps.at(-1),state:window.aquarium,errors:document.querySelector('#loading')?.textContent})));throw e;});const data=await page.evaluate(()=>({steps:window.burstProbe.steps,frames:window.burstProbe.frames,count:window.burstProbe.count,diagnostics:window.lab?.state||window.aquarium}));
 const at=[.1,.25,.5].map(t=>{const s=data.steps.reduce((a,b)=>Math.abs(a.after-t)<Math.abs(b.after-t)?a:b),b=s.bodies;return {t,radialMean:round(mean(b.map(b=>b.radial))),radial90:round(q(b.map(b=>b.radial),.9)),outward:round(mean(b.map(b=>+(b.radial>0)))),speed50:round(q(b.map(b=>b.speed),.5)),speed90:round(q(b.map(b=>b.speed),.9)),angular50:round(q(b.map(b=>b.angular),.5)),angular90:round(q(b.map(b=>b.angular),.9)),supported:s.states.filter(b=>b.regime!=='airborne').length,sleep:b.filter(b=>b.sleep).length,cached:s.states.filter(b=>b.cached).length};});
 const summary={run,scenario,count:data.count,at,speedRatio:round(at[1].speed50/at[0].speed50),meanSpeedRatio:round(mean(data.steps[14].bodies.map(b=>b.speed))/mean(data.steps[5].bodies.map(b=>b.speed))),steps:data.steps.length,supportedBodySteps:data.steps.reduce((n,s)=>n+s.states.filter(b=>b.regime!=='airborne').length,0),solver:[...new Set(data.steps.flatMap(s=>s.states.map(b=>b.solver)))],pgs:[...new Set(data.steps.map(s=>s.pgs))],sleep:data.steps.flatMap(s=>s.bodies).filter(b=>b.sleep).length,cached:data.steps.flatMap(s=>s.states).filter(b=>b.cached).length};results.push(summary);console.log(JSON.stringify(summary));await writeFile(`verify/burst-${run}/${scenario}.json`,JSON.stringify({summary,...data},null,2));
 }}assert.deepEqual(errors,[]);if(!shots)await writeFile('verify/burst-comparison.json',JSON.stringify(results,null,2));}finally{await browser.close();}
