import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-webgpu','--use-angle=metal','--ignore-gpu-blocklist']}),page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1.5}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.renderFrames=[];let last,started;function sample(t){if(window.burstProbe?.start>=0){started??=t;if(last!==undefined)window.renderFrames.push({wallTime:(t-started)/1000,ms:t-last});last=t;}requestAnimationFrame(sample);}requestAnimationFrame(sample);});
const base=process.env.VERIFY_URL||'http://localhost:4175/',median=a=>a.sort((a,b)=>a-b)[Math.floor(a.length/2)];
async function release(level,count,stop=Infinity){await page.goto(`${base}?${process.env.PROFILE?"fourWallPerf&":""}burstProbe&burstUntil=0#/lab/shatter?level=${level}`);await page.waitForFunction(()=>window.lab?.ready,null,{timeout:90000});await page.evaluate(count=>window.lab.setReveal({count,freeze:true}),count);await page.keyboard.press('r');await page.waitForFunction(()=>window.lab.state.elapsed===0&&!window.lab.state.broken);await page.evaluate(stop=>window.burstProbe.stopAt=stop,stop);const p=await page.evaluate(()=>window.lab.state.paneCenter);await page.mouse.click(p.x,p.y);const s=await page.evaluate(()=>window.lab.state);assert.equal(s.shardCount,s.cellCount);assert.ok(s.cellsPerBody.every(n=>n===1));assert.equal(s.bodyCount,s.cellCount+2);console.log(`HIST L${level} count=${count} cells=${s.cellCount} bodies=${s.shardCount} histogram(1/2/3-5/6+)=${s.shardCount}/0/0/0`);await page.evaluate(()=>window.lab.setReveal({freeze:false}));return s;}
try{for(const level of (process.env.LEVELS||"1,2,3").split(",").map(Number))for(const count of (process.env.COUNTS||"220,600").split(",").map(Number)){const s=await release(level,count);await page.waitForFunction(()=>window.burstProbe.frames.at(-1)?.wallTime>6.1,null,{timeout:90000});const frames=await page.evaluate(()=>window.burstProbe.frames),renderFrames=await page.evaluate(()=>window.renderFrames),fps=(a,b)=>1000/median(renderFrames.filter(f=>f.wallTime>=a&&f.wallTime<b).map(f=>f.ms));const result={level,count,airborne:fps(.1,1.5),settled:fps(5,6),awake:(await page.evaluate(()=>window.lab.state)).awakeCount};const air=frames.filter(f=>f.wallTime>=.1&&f.wallTime<1.5);result.physicsMs=(air.at(-1).physics-air[0].physics)/(air.length-1);result.rapierMs=(air.at(-1).rapier-air[0].rapier)/(air.length-1);results.push(result);console.log(`FPS L${level} ${count}: airborne=${result.airborne.toFixed(2)} settled=${result.settled.toFixed(2)} awake=${result.awake}${process.env.PROFILE?` physics=${result.physicsMs.toFixed(2)}ms rapier=${result.rapierMs.toFixed(2)}ms`:""}`);}
await mkdir('verify/perf-after',{recursive:true});await writeFile('verify/perf-after/lab-cells-results.json',JSON.stringify(results,null,2));
await release(3,220,.3);await page.waitForFunction(()=>window.lab.state.elapsed>=.3-1e-8);await page.mouse.move(780,470);await page.mouse.wheel(0,-650);await page.waitForTimeout(600);await page.screenshot({path:'verify/perf-after/lab-L3-cells-030.png',clip:{x:350,y:210,width:800,height:570}});assert.deepEqual(errors,[]);
}finally{await browser.close();}
