import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.VERIFY_URL||'http://localhost:4175/',runs=(process.env.RUNS||'before,after').split(','),cases=(process.env.CASES||'L2,L3,main').split(','),shots=process.argv.includes('--shots');
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-webgpu','--use-angle=metal','--ignore-gpu-blocklist']}),page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1.5}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const q=(a,p)=>[...a].sort((a,b)=>a-b)[Math.floor((a.length-1)*p)]||0,mean=a=>a.reduce((a,b)=>a+b,0)/a.length,round=n=>+n.toFixed(4);
async function release(run,c,stop=Infinity){await page.goto(`${base}?burstProbe&burstUntil=1&labRelease=${run}&camera=default${c==='main'?'':`#/lab/shatter?level=${c[1]}`}`);
 if(c==='main'){await page.waitForFunction(()=>window.aquarium?.elapsed>2,null,{timeout:90000});await page.keyboard.press('Space');}
 else{await page.waitForFunction(()=>window.lab?.ready,null,{timeout:90000});await page.evaluate(()=>window.lab.setReveal({freeze:true}));await page.keyboard.press('r');await page.waitForFunction(()=>window.lab.state.elapsed===0&&!window.lab.state.broken);await page.evaluate(stop=>window.burstProbe.stopAt=stop,stop);const p=await page.evaluate(()=>window.lab.state.paneCenter);await page.mouse.click(p.x,p.y);await page.evaluate(()=>window.lab.setReveal({freeze:false}));}}
try{for(const run of runs){const dir=`verify/impulse-${run}`;await mkdir(dir,{recursive:true});for(const c of cases){
 if(shots){if(c!=='L3')continue;for(const t of [.1,.25,.5,1,2]){await release(run,c,t);await page.waitForFunction(t=>window.lab.state.elapsed>=t-1e-8,t);await page.waitForTimeout(120);const name=`${run==='after'?'verify/perf-after':dir}/lab-L3-impulse-${String(Math.round(t*100)).padStart(3,'0')}`;await page.screenshot({path:name+'.png'});await writeFile(name+'.json',JSON.stringify(await page.evaluate(()=>window.lab.state),null,2));console.log(`FRAME ${run} L3 ${t.toFixed(2)}s ${name}.png`);}continue;}
 await release(run,c);await page.waitForFunction(()=>window.burstProbe.frames.at(-1)?.time>=6.1,null,{timeout:90000});const d=await page.evaluate(()=>({steps:window.burstProbe.steps,frames:window.burstProbe.frames,state:window.lab?.state||window.aquarium}));
 const at=[.1,.25,.5].map(t=>{const s=d.steps[Math.round(t*60)-1],b=s.bodies;return {t,radialMean:round(mean(b.map(b=>b.radial))),radial90:round(q(b.map(b=>b.radial),.9)),outward:round(mean(b.map(b=>+(b.radial>0)))),speed50:round(q(b.map(b=>b.speed),.5)),angular90:round(q(b.map(b=>b.angular),.9))};});
 const radius=[.25,.5,1].map(t=>{const b=d.steps[Math.round(t*60)-1].bodies;return {t,r90:round(q(b.map(b=>b.radius),.9)),core90:round(q(b.filter(b=>b.homeRadius<.35).map(b=>b.radius),.9))};});
 const fps=(a,b)=>round(1000/q(d.frames.filter(f=>f.wallTime>=a&&f.wallTime<b).map(f=>f.ms),.5));
 const summary={run,case:c,count:d.steps[0].bodies.length,at,radius,retention:round(at[1].speed50/at[0].speed50),fpsAirborne:fps(.1,1.5),fpsSettled:fps(5,6),awake:d.state.awakeCount??d.state.awakeShards,defaults:{impulse:d.state.impulse,falloff:d.state.falloff,forward:d.state.forward,spin:d.state.spin}};
 console.log(JSON.stringify(summary));await writeFile(`${dir}/${c}.json`,JSON.stringify({summary,...d},null,2));
 }}assert.deepEqual(errors,[]);}finally{await browser.close();}
